# Generated by Django 5.0.6 on 2024-08-13 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Joylashuv')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Qavat raqami')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.buildings')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Uy raqami')),
                ('room', models.IntegerField(verbose_name='Uydagi xonalar soni')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.floor')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=255, verbose_name='F.I.SH')),
                ('telefon', models.IntegerField(verbose_name='Telfon')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.buildings', verbose_name='Bino')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.floor', verbose_name='Qavat')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.home', verbose_name='Uy')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.location', verbose_name='Joylashuv')),
            ],
        ),
        migrations.AddField(
            model_name='buildings',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.location'),
        ),
    ]
