# Generated by Django 5.0.6 on 2024-08-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='term',
            field=models.CharField(choices=[('5-yil', '5 yil'), ('6-yil', '6 yil'), ('7-yil', '7 yil'), ('8-yil', '8 yil'), ('9-yil', '9 yil'), ('10-yil', '10 yil'), ('11-yil', '11 yil'), ('12-yil', '13 yil'), ('13-yil', '13 yil'), ('14-yil', '14 yil'), ('15-yil', '15 yil'), ('16-yil', '16 yil'), ('17-yil', '17 yil'), ('18-yil', '18 yil'), ('19-yil', '19 yil'), ('20-yil', '20 yil')], default='5-yil', max_length=50),
        ),
    ]
