# Generated by Django 5.0.6 on 2024-08-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_clients_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='oylik_tolov',
            field=models.DecimalField(decimal_places=2, default=2, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='square',
            field=models.BigIntegerField(default=2, verbose_name='m² maydon narxi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='total_area',
            field=models.BigIntegerField(default=2, verbose_name='Umumiy maydoni'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clients',
            name='term',
            field=models.CharField(choices=[('---', '---'), ('5-yil', '5 yil'), ('6-yil', '6 yil'), ('7-yil', '7 yil'), ('8-yil', '8 yil'), ('9-yil', '9 yil'), ('10-yil', '10 yil'), ('11-yil', '11 yil'), ('12-yil', '13 yil'), ('13-yil', '13 yil'), ('14-yil', '14 yil'), ('15-yil', '15 yil'), ('16-yil', '16 yil'), ('17-yil', '17 yil'), ('18-yil', '18 yil'), ('19-yil', '19 yil'), ('20-yil', '20 yil')], default='---', max_length=50, verbose_name="To'lov muddati"),
        ),
    ]
