# Generated by Django 5.0.6 on 2024-08-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_clients_term'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildings',
            options={'verbose_name': 'Bino', 'verbose_name_plural': 'Binolar'},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Mijoz', 'verbose_name_plural': 'Mijozlar'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name': 'Qavat', 'verbose_name_plural': 'Qavatlar'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Uy', 'verbose_name_plural': 'Uylar'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Joylashuv', 'verbose_name_plural': 'Joylashuvlar'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AddField(
            model_name='clients',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
