# Generated by Django 5.0.6 on 2024-08-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_buildings_options_alter_clients_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='noactive',
            field=models.BooleanField(default=True),
        ),
    ]
