# Generated by Django 5.0.6 on 2024-08-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_clients_noactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clients',
            name='noactive',
            field=models.BooleanField(default=False),
        ),
    ]
