# Generated by Django 5.0.6 on 2024-08-14 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_clients_active_alter_clients_noactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='noactive',
        ),
    ]
