# Generated by Django 5.0.6 on 2024-08-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_clients_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='active',
        ),
        migrations.AddField(
            model_name='clients',
            name='status',
            field=models.CharField(choices=[('0', 'Sotib Olmoqchi'), ('1', "O'ylab Ko'rmoqchi")], default='0', max_length=20),
        ),
    ]
