# Generated by Django 5.0.6 on 2024-08-14 06:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_clients_active_clients_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.home', verbose_name='Uy'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='oylik_tolov',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.CharField(choices=[('1', 'Sotib Olmoqchi'), ('0', "O'ylab Ko'rmoqchi")], default='0', max_length=20),
        ),
    ]
