# Generated by Django 5.0.6 on 2024-08-14 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_clients_home_alter_clients_oylik_tolov_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='home',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.home', verbose_name='Uy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clients',
            name='oylik_tolov',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
