# Generated by Django 5.0.6 on 2024-08-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_clients_home_alter_clients_oylik_tolov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.CharField(choices=[('0', "O'ylab Ko'rmoqchi"), ('1', 'Sotib Olmoqchi'), ('2', 'Sotib oldi')], default='0', max_length=20),
        ),
    ]
